package com.pimubi.storedev.services;

import com.pimubi.storedev.models.Order;
import com.pimubi.storedev.models.OrderItem;
import com.pimubi.storedev.repository.OrderItemRepository;
import com.pimubi.storedev.repository.OrderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class OrderService {
    private final OrderRepository orderRepository;
    private final OrderItemRepository orderItemRepository;

    @Autowired
    public OrderService(OrderRepository orderRepository, OrderItemRepository orderItemRepository) {
        this.orderRepository = orderRepository;
        this.orderItemRepository = orderItemRepository;
    }

    public Order placeOrder(Order order, List<OrderItem> orderItems) {
        // Save the order to get the order ID generated by the database
        Order savedOrder = orderRepository.save(order);

        // Associate each OrderItem with the saved Order and save them to the database
        for (OrderItem orderItem : orderItems) {
            orderItem.setOrder(savedOrder);
            orderItemRepository.save(orderItem);
        }

        return savedOrder;
    }
}

